language: node_js
node_js:
  - 10.15.0
before_install:
  - stty columns 120
script:
  - git remote set-branches --add origin $TRAVIS_BRANCH
  - git checkout origin/ci-test
  - git fetch
  - git status
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT
  - node .travis.js
