language: node_js
node_js:
  - 10.13.0
before_install:
  - stty columns 120
script:
  - git remote set-branches --add origin $TRAVIS_BRANCH
  - git fetch
  - git status
  - echo $TRAVIS_COMMIT_RANGE
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_COMMIT
- node ci.js
