name: Validation

on:
    push:
        branches: [master]
    pull_request_target:

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              if: github.event_name == 'push'
            - uses: actions/checkout@v2
              if: github.event_name == 'pull_request_target'
              with:
                  ref: ${{github.event.pull_request.head.ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}
            - name: Use Node.js 15
              uses: actions/setup-node@v1
              with:
                  node-version: "15"
            - name: Use yarn 2
              run: yarn set version berry
            - name: Validate
              run: yarn dlx --quiet js-org-validate
            - name: "Comment PR"
              uses: actions/github-script@v3
              if: always() && github.event_name == 'pull_request_target'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const fs = require("fs");
                      const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
                      github.issues.createComment(
                        { 
                          issue_number,
                          owner,
                          repo,
                          body: await fs.promises.readFile(`${process.env.GITHUB_WORKSPACE}/pull_request_comment.md`, "utf-8") 
                        }
                      );
            - name: "Comment commit"
              uses: actions/github-script@v3
              if: always() && github.event_name == 'push'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const fs = require("fs");
                      const { sha, repo: { owner, repo }  } = context;
                      github.repos.createCommitComment({
                        owner,
                        repo,
                        commit_sha: sha,
                        body: await fs.promises.readFile(`${process.env.GITHUB_WORKSPACE}/commit_comment.md`, "utf-8") 
                      })
